export type {
  ResourceType,
  Resources,
  Terrain,
  Territory,
  Continent,
  Player,
  TechBranch,
  TechLevels,
  TechProgress,
  ShortageCounters,
  AgreementType,
  Agreement,
  Sanction,
  UNResolutionType,
  UNResolution,
  ActiveResolution,
  DiplomaticMessage,
  WorldEventType,
  WorldEvent,
  GameMap,
  GameState,
  GamePhase,
  TurnPhase,
  AttackAction,
  ReinforceAction,
  ResearchAction,
  BuildFortAction,
  LaunchMissileAction,
  LaunchNukeAction,
  TradeAction,
  SanctionAction,
  SpyOperation,
  SpyAction,
  CyberattackAction,
  DiplomacyActionType,
  DiplomacyAction,
  PlayerAction,
  BattleEvent,
  ConquestEvent,
  ReinforcementEvent,
  EliminationEvent,
  VictoryEvent,
  ResearchEvent,
  MissileStrikeEvent,
  NukeEvent,
  DiplomacyEvent,
  SpyEvent,
  WorldEventOccurrence,
  ResourceProductionEvent,
  ShortageEvent,
  GameEvent,
  TurnResult,
} from './types.js';

export {
  EMPTY_RESOURCES,
  RESOURCE_STOCKPILE_CAP,
  TECH_COSTS,
  MAX_TECH_LEVEL,
  SHORTAGE_WARNING_TURNS,
  SHORTAGE_PENALTY_TURNS,
  SHORTAGE_CRITICAL_TURNS,
  REPUTATION_INITIAL,
  REPUTATION_MAX,
  REPUTATION_RECOVERY_PER_TURN,
  REPUTATION_NO_TREATIES_THRESHOLD,
  REPUTATION_DEFECTION_THRESHOLD,
  REPUTATION_DOUBLE_COST_THRESHOLD,
  BREAK_TRADE_DEAL_REPUTATION,
  BREAK_NAP_REPUTATION,
  BREAK_ALLIANCE_REPUTATION,
  DIPLOMACY_MESSAGE_BASE_COST,
  DIPLOMACY_MESSAGE_INTEL1_COST,
  EVENT_MIN_INTERVAL,
  EVENT_MAX_INTERVAL,
  DOMINANCE_THRESHOLD,
  MAX_TURNS,
  FORT_DEFENSE_BONUS,
  MAX_FORT_LEVEL,
  MOUNTAIN_DEFENSE_BONUS,
  ALLIANCE_DEFENSE_RATIO,
  PACT_BREAKER_ATTACK_PENALTY,
  MISSILE_RANGE,
  MISSILE_TROOP_KILL_RATIO,
  MISSILE_OIL_COST,
  MISSILE_MINERAL_COST,
  NUKE_OIL_COST,
  NUKE_MINERAL_COST,
  NUKE_PRIMARY_KILL_RATIO,
  NUKE_COLLATERAL_KILL_RATIO,
  NUKE_FALLOUT_TURNS,
  NUKE_WAR_ECONOMY_TURNS,
  NUKE_WAR_ECONOMY_MULTIPLIER,
  FORT_MINERAL_COST,
  TROOP_MONEY_COST,
} from './types.js';

export {
  createDefaultMap,
  areAdjacent,
  getNeighbors,
  getPlayerTerritories,
  playerOwnsContinent,
} from './map.js';

export { validateAction } from './validation.js';
export { resolveCombat } from './combat.js';
export { calculateReinforcements } from './reinforcements.js';
export { resolveTurn } from './turn.js';
export { createGame, assignTerritories } from './game.js';
