import type { GameMap, Territory, Continent, Terrain, Resources } from './types.js';

// ── Raw Map Data (Country-level world map – 146 territories, 17 regions) ──

interface TerritoryDef {
  id: string;
  name: string;
  continentId: string;
  terrain: Terrain;
  resources: Partial<Resources>;
}

interface ContinentDef {
  id: string;
  name: string;
  bonusTroops: number;
}

const CONTINENTS: ContinentDef[] = [
  { id: 'north_america', name: 'North America', bonusTroops: 5 },
  { id: 'central_america', name: 'Central America', bonusTroops: 3 },
  { id: 'south_america', name: 'South America', bonusTroops: 5 },
  { id: 'western_europe', name: 'Western Europe', bonusTroops: 5 },
  { id: 'northern_europe', name: 'Northern Europe', bonusTroops: 3 },
  { id: 'eastern_europe', name: 'Eastern Europe', bonusTroops: 4 },
  { id: 'former_soviet', name: 'Former Soviet', bonusTroops: 6 },
  { id: 'middle_east', name: 'Middle East', bonusTroops: 4 },
  { id: 'north_africa', name: 'North Africa', bonusTroops: 3 },
  { id: 'west_africa', name: 'West Africa', bonusTroops: 4 },
  { id: 'east_africa', name: 'East & South Africa', bonusTroops: 5 },
  { id: 'central_africa', name: 'Central Africa', bonusTroops: 4 },
  { id: 'central_asia', name: 'Central Asia', bonusTroops: 5 },
  { id: 'south_asia', name: 'South Asia', bonusTroops: 3 },
  { id: 'east_asia', name: 'East Asia', bonusTroops: 5 },
  { id: 'southeast_asia', name: 'Southeast Asia', bonusTroops: 4 },
  { id: 'oceania', name: 'Oceania', bonusTroops: 2 },
];

const TERRITORIES: TerritoryDef[] = [
  // North America (5)
  { id: 'canada', name: 'Canada', continentId: 'north_america', terrain: 'plains', resources: { food: 2, money: 2 } },
  { id: 'united_states_of_america', name: 'United States of America', continentId: 'north_america', terrain: 'plains', resources: { food: 3, money: 3 } },
  { id: 'greenland', name: 'Greenland', continentId: 'north_america', terrain: 'coastal', resources: { money: 1 } },
  { id: 'mexico', name: 'Mexico', continentId: 'north_america', terrain: 'plains', resources: { oil: 1, food: 2, money: 1 } },
  { id: 'cuba', name: 'Cuba', continentId: 'north_america', terrain: 'coastal', resources: { food: 1, money: 1 } },

  // Central America (7)
  { id: 'panama', name: 'Panama', continentId: 'central_america', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'costa_rica', name: 'Costa Rica', continentId: 'central_america', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'nicaragua', name: 'Nicaragua', continentId: 'central_america', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'honduras', name: 'Honduras', continentId: 'central_america', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'el_salvador', name: 'El Salvador', continentId: 'central_america', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'guatemala', name: 'Guatemala', continentId: 'central_america', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'belize', name: 'Belize', continentId: 'central_america', terrain: 'coastal', resources: { food: 1, money: 1 } },

  // South America (12)
  { id: 'argentina', name: 'Argentina', continentId: 'south_america', terrain: 'plains', resources: { food: 3, money: 1 } },
  { id: 'chile', name: 'Chile', continentId: 'south_america', terrain: 'mountains', resources: { minerals: 3, food: 1, money: 1 } },
  { id: 'uruguay', name: 'Uruguay', continentId: 'south_america', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'brazil', name: 'Brazil', continentId: 'south_america', terrain: 'plains', resources: { oil: 2, minerals: 2, food: 3, money: 2 } },
  { id: 'bolivia', name: 'Bolivia', continentId: 'south_america', terrain: 'mountains', resources: { minerals: 1, food: 1 } },
  { id: 'peru', name: 'Peru', continentId: 'south_america', terrain: 'mountains', resources: { minerals: 2, food: 1, money: 1 } },
  { id: 'colombia', name: 'Colombia', continentId: 'south_america', terrain: 'mountains', resources: { oil: 1, food: 1, money: 1 } },
  { id: 'venezuela', name: 'Venezuela', continentId: 'south_america', terrain: 'plains', resources: { oil: 3, food: 1, money: 1 } },
  { id: 'guyana', name: 'Guyana', continentId: 'south_america', terrain: 'plains', resources: { food: 1 } },
  { id: 'suriname', name: 'Suriname', continentId: 'south_america', terrain: 'plains', resources: { food: 1 } },
  { id: 'ecuador', name: 'Ecuador', continentId: 'south_america', terrain: 'mountains', resources: { oil: 1, food: 1, money: 1 } },
  { id: 'paraguay', name: 'Paraguay', continentId: 'south_america', terrain: 'plains', resources: { food: 1, money: 1 } },

  // Western Europe (11)
  { id: 'france', name: 'France', continentId: 'western_europe', terrain: 'coastal', resources: { food: 3, money: 3 } },
  { id: 'germany', name: 'Germany', continentId: 'western_europe', terrain: 'plains', resources: { food: 2, money: 3 } },
  { id: 'belgium', name: 'Belgium', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'netherlands', name: 'Netherlands', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 2 } },
  { id: 'portugal', name: 'Portugal', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'spain', name: 'Spain', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 2 } },
  { id: 'ireland', name: 'Ireland', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'italy', name: 'Italy', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 2 } },
  { id: 'denmark', name: 'Denmark', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'united_kingdom', name: 'United Kingdom', continentId: 'western_europe', terrain: 'coastal', resources: { food: 1, money: 3 } },
  { id: 'iceland', name: 'Iceland', continentId: 'western_europe', terrain: 'coastal', resources: { money: 1 } },

  // Northern Europe (6)
  { id: 'norway', name: 'Norway', continentId: 'northern_europe', terrain: 'mountains', resources: { oil: 2, food: 1, money: 1 } },
  { id: 'sweden', name: 'Sweden', continentId: 'northern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'lithuania', name: 'Lithuania', continentId: 'northern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'latvia', name: 'Latvia', continentId: 'northern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'estonia', name: 'Estonia', continentId: 'northern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'finland', name: 'Finland', continentId: 'northern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },

  // Eastern Europe (11)
  { id: 'poland', name: 'Poland', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'austria', name: 'Austria', continentId: 'eastern_europe', terrain: 'mountains', resources: { food: 1, money: 1 } },
  { id: 'hungary', name: 'Hungary', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'romania', name: 'Romania', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'bulgaria', name: 'Bulgaria', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'greece', name: 'Greece', continentId: 'eastern_europe', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'albania', name: 'Albania', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'switzerland', name: 'Switzerland', continentId: 'eastern_europe', terrain: 'mountains', resources: { food: 1, money: 2 } },
  { id: 'slovakia', name: 'Slovakia', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'czechia', name: 'Czechia', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'bosnia_and_herz', name: 'Bosnia and Herz.', continentId: 'eastern_europe', terrain: 'plains', resources: { food: 1, money: 1 } },

  // Former Soviet (13)
  { id: 'russia', name: 'Russia', continentId: 'former_soviet', terrain: 'plains', resources: { oil: 3, minerals: 2, food: 1, money: 2 } },
  { id: 'armenia', name: 'Armenia', continentId: 'former_soviet', terrain: 'mountains', resources: { food: 1, money: 1 } },
  { id: 'belarus', name: 'Belarus', continentId: 'former_soviet', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'ukraine', name: 'Ukraine', continentId: 'former_soviet', terrain: 'plains', resources: { food: 3, money: 1 } },
  { id: 'moldova', name: 'Moldova', continentId: 'former_soviet', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'turkey', name: 'Turkey', continentId: 'former_soviet', terrain: 'plains', resources: { food: 2, money: 1 } },
  { id: 'croatia', name: 'Croatia', continentId: 'former_soviet', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'azerbaijan', name: 'Azerbaijan', continentId: 'former_soviet', terrain: 'plains', resources: { oil: 1, food: 1, money: 1 } },
  { id: 'georgia', name: 'Georgia', continentId: 'former_soviet', terrain: 'mountains', resources: { food: 1, money: 1 } },
  { id: 'slovenia', name: 'Slovenia', continentId: 'former_soviet', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'macedonia', name: 'Macedonia', continentId: 'former_soviet', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'serbia', name: 'Serbia', continentId: 'former_soviet', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'montenegro', name: 'Montenegro', continentId: 'former_soviet', terrain: 'coastal', resources: { food: 1, money: 1 } },

  // Middle East (8)
  { id: 'jordan', name: 'Jordan', continentId: 'middle_east', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'united_arab_emirates', name: 'United Arab Emirates', continentId: 'middle_east', terrain: 'plains', resources: { oil: 3, money: 2 } },
  { id: 'iraq', name: 'Iraq', continentId: 'middle_east', terrain: 'plains', resources: { oil: 3, food: 1, money: 1 } },
  { id: 'oman', name: 'Oman', continentId: 'middle_east', terrain: 'plains', resources: { oil: 1, money: 1 } },
  { id: 'iran', name: 'Iran', continentId: 'middle_east', terrain: 'plains', resources: { oil: 3, food: 1, money: 1 } },
  { id: 'syria', name: 'Syria', continentId: 'middle_east', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'yemen', name: 'Yemen', continentId: 'middle_east', terrain: 'plains', resources: { food: 1 } },
  { id: 'saudi_arabia', name: 'Saudi Arabia', continentId: 'middle_east', terrain: 'plains', resources: { oil: 3, money: 2 } },

  // North Africa (7)
  { id: 'w_sahara', name: 'W. Sahara', continentId: 'north_africa', terrain: 'plains', resources: { money: 1 } },
  { id: 'mauritania', name: 'Mauritania', continentId: 'north_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'tunisia', name: 'Tunisia', continentId: 'north_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'algeria', name: 'Algeria', continentId: 'north_africa', terrain: 'plains', resources: { oil: 2, food: 1, money: 1 } },
  { id: 'morocco', name: 'Morocco', continentId: 'north_africa', terrain: 'plains', resources: { minerals: 1, food: 1, money: 1 } },
  { id: 'egypt', name: 'Egypt', continentId: 'north_africa', terrain: 'plains', resources: { oil: 1, food: 1, money: 1 } },
  { id: 'libya', name: 'Libya', continentId: 'north_africa', terrain: 'plains', resources: { oil: 3, money: 1 } },

  // West Africa (12)
  { id: 'senegal', name: 'Senegal', continentId: 'west_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'mali', name: 'Mali', continentId: 'west_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'benin', name: 'Benin', continentId: 'west_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'niger', name: 'Niger', continentId: 'west_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'nigeria', name: 'Nigeria', continentId: 'west_africa', terrain: 'plains', resources: { oil: 3, food: 2, money: 1 } },
  { id: 'togo', name: 'Togo', continentId: 'west_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'ghana', name: 'Ghana', continentId: 'west_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'cte_divoire', name: "Côte d'Ivoire", continentId: 'west_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'guinea', name: 'Guinea', continentId: 'west_africa', terrain: 'plains', resources: { minerals: 1, food: 1 } },
  { id: 'liberia', name: 'Liberia', continentId: 'west_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'sierra_leone', name: 'Sierra Leone', continentId: 'west_africa', terrain: 'plains', resources: { minerals: 1, food: 1 } },
  { id: 'burkina_faso', name: 'Burkina Faso', continentId: 'west_africa', terrain: 'plains', resources: { food: 1 } },

  // East & South Africa (15)
  { id: 'tanzania', name: 'Tanzania', continentId: 'east_africa', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'somalia', name: 'Somalia', continentId: 'east_africa', terrain: 'coastal', resources: { food: 1 } },
  { id: 'kenya', name: 'Kenya', continentId: 'east_africa', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'sudan', name: 'Sudan', continentId: 'east_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'zimbabwe', name: 'Zimbabwe', continentId: 'east_africa', terrain: 'plains', resources: { minerals: 1, food: 1 } },
  { id: 'zambia', name: 'Zambia', continentId: 'east_africa', terrain: 'plains', resources: { minerals: 1, food: 1 } },
  { id: 'malawi', name: 'Malawi', continentId: 'east_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'mozambique', name: 'Mozambique', continentId: 'east_africa', terrain: 'coastal', resources: { food: 1 } },
  { id: 'burundi', name: 'Burundi', continentId: 'east_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'madagascar', name: 'Madagascar', continentId: 'east_africa', terrain: 'coastal', resources: { food: 1 } },
  { id: 'eritrea', name: 'Eritrea', continentId: 'east_africa', terrain: 'coastal', resources: { food: 1 } },
  { id: 'ethiopia', name: 'Ethiopia', continentId: 'east_africa', terrain: 'mountains', resources: { food: 1, money: 1 } },
  { id: 'uganda', name: 'Uganda', continentId: 'east_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'rwanda', name: 'Rwanda', continentId: 'east_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 's_sudan', name: 'S. Sudan', continentId: 'east_africa', terrain: 'plains', resources: { food: 1 } },

  // Central Africa (11)
  { id: 'dem_rep_congo', name: 'Dem. Rep. Congo', continentId: 'central_africa', terrain: 'plains', resources: { minerals: 3, food: 1 } },
  { id: 'chad', name: 'Chad', continentId: 'central_africa', terrain: 'plains', resources: { oil: 1, food: 1 } },
  { id: 'south_africa', name: 'South Africa', continentId: 'central_africa', terrain: 'plains', resources: { minerals: 3, food: 1, money: 1 } },
  { id: 'botswana', name: 'Botswana', continentId: 'central_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'namibia', name: 'Namibia', continentId: 'central_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'cameroon', name: 'Cameroon', continentId: 'central_africa', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'central_african_rep', name: 'Central African Rep.', continentId: 'central_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'congo', name: 'Congo', continentId: 'central_africa', terrain: 'plains', resources: { oil: 1, food: 1 } },
  { id: 'gabon', name: 'Gabon', continentId: 'central_africa', terrain: 'plains', resources: { oil: 1, minerals: 1, food: 1 } },
  { id: 'eq_guinea', name: 'Eq. Guinea', continentId: 'central_africa', terrain: 'plains', resources: { food: 1 } },
  { id: 'angola', name: 'Angola', continentId: 'central_africa', terrain: 'plains', resources: { oil: 2, food: 1, money: 1 } },

  // Central Asia (7)
  { id: 'kazakhstan', name: 'Kazakhstan', continentId: 'central_asia', terrain: 'plains', resources: { oil: 2, minerals: 2, food: 1, money: 1 } },
  { id: 'uzbekistan', name: 'Uzbekistan', continentId: 'central_asia', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'mongolia', name: 'Mongolia', continentId: 'central_asia', terrain: 'mountains', resources: { minerals: 1, food: 1 } },
  { id: 'afghanistan', name: 'Afghanistan', continentId: 'central_asia', terrain: 'mountains', resources: { food: 1 } },
  { id: 'tajikistan', name: 'Tajikistan', continentId: 'central_asia', terrain: 'mountains', resources: { food: 1 } },
  { id: 'kyrgyzstan', name: 'Kyrgyzstan', continentId: 'central_asia', terrain: 'mountains', resources: { food: 1 } },
  { id: 'turkmenistan', name: 'Turkmenistan', continentId: 'central_asia', terrain: 'plains', resources: { food: 1, money: 1 } },

  // South Asia (5)
  { id: 'india', name: 'India', continentId: 'south_asia', terrain: 'plains', resources: { minerals: 2, food: 3, money: 2 } },
  { id: 'bangladesh', name: 'Bangladesh', continentId: 'south_asia', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'nepal', name: 'Nepal', continentId: 'south_asia', terrain: 'mountains', resources: { food: 1 } },
  { id: 'pakistan', name: 'Pakistan', continentId: 'south_asia', terrain: 'plains', resources: { food: 2, money: 1 } },
  { id: 'sri_lanka', name: 'Sri Lanka', continentId: 'south_asia', terrain: 'coastal', resources: { food: 1, money: 1 } },

  // East Asia (5)
  { id: 'north_korea', name: 'North Korea', continentId: 'east_asia', terrain: 'coastal', resources: { food: 1 } },
  { id: 'south_korea', name: 'South Korea', continentId: 'east_asia', terrain: 'coastal', resources: { food: 1, money: 2 } },
  { id: 'china', name: 'China', continentId: 'east_asia', terrain: 'plains', resources: { minerals: 3, food: 2, money: 3 } },
  { id: 'taiwan', name: 'Taiwan', continentId: 'east_asia', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'japan', name: 'Japan', continentId: 'east_asia', terrain: 'coastal', resources: { food: 1, money: 3 } },

  // Southeast Asia (8)
  { id: 'indonesia', name: 'Indonesia', continentId: 'southeast_asia', terrain: 'coastal', resources: { oil: 1, minerals: 2, food: 2, money: 1 } },
  { id: 'cambodia', name: 'Cambodia', continentId: 'southeast_asia', terrain: 'plains', resources: { food: 1, money: 1 } },
  { id: 'thailand', name: 'Thailand', continentId: 'southeast_asia', terrain: 'coastal', resources: { food: 3, money: 1 } },
  { id: 'laos', name: 'Laos', continentId: 'southeast_asia', terrain: 'plains', resources: { food: 1 } },
  { id: 'myanmar', name: 'Myanmar', continentId: 'southeast_asia', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'vietnam', name: 'Vietnam', continentId: 'southeast_asia', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'philippines', name: 'Philippines', continentId: 'southeast_asia', terrain: 'coastal', resources: { minerals: 1, food: 1, money: 1 } },
  { id: 'malaysia', name: 'Malaysia', continentId: 'southeast_asia', terrain: 'coastal', resources: { oil: 1, food: 1, money: 2 } },

  // Oceania (3)
  { id: 'papua_new_guinea', name: 'Papua New Guinea', continentId: 'oceania', terrain: 'coastal', resources: { food: 1 } },
  { id: 'new_zealand', name: 'New Zealand', continentId: 'oceania', terrain: 'coastal', resources: { food: 1, money: 1 } },
  { id: 'australia', name: 'Australia', continentId: 'oceania', terrain: 'coastal', resources: { minerals: 3, food: 2, money: 2 } },

];

const EDGES: [string, string][] = [
  ['afghanistan', 'china'],
  ['afghanistan', 'india'],
  ['afghanistan', 'iran'],
  ['afghanistan', 'kyrgyzstan'],
  ['afghanistan', 'pakistan'],
  ['afghanistan', 'tajikistan'],
  ['afghanistan', 'turkmenistan'],
  ['afghanistan', 'uzbekistan'],
  ['albania', 'bosnia_and_herz'],
  ['albania', 'bulgaria'],
  ['albania', 'croatia'],
  ['albania', 'greece'],
  ['albania', 'italy'],
  ['albania', 'macedonia'],
  ['albania', 'montenegro'],
  ['albania', 'serbia'],
  ['algeria', 'libya'],
  ['algeria', 'mali'],
  ['algeria', 'mauritania'],
  ['algeria', 'morocco'],
  ['algeria', 'niger'],
  ['algeria', 'spain'],
  ['algeria', 'tunisia'],
  ['algeria', 'w_sahara'],
  ['angola', 'botswana'],
  ['angola', 'congo'],
  ['angola', 'dem_rep_congo'],
  ['angola', 'gabon'],
  ['angola', 'namibia'],
  ['angola', 'zambia'],
  ['argentina', 'bolivia'],
  ['argentina', 'brazil'],
  ['argentina', 'chile'],
  ['argentina', 'paraguay'],
  ['argentina', 'uruguay'],
  ['armenia', 'azerbaijan'],
  ['armenia', 'georgia'],
  ['armenia', 'iran'],
  ['armenia', 'iraq'],
  ['armenia', 'russia'],
  ['armenia', 'turkey'],
  ['australia', 'indonesia'],
  ['australia', 'new_zealand'],
  ['australia', 'papua_new_guinea'],
  ['austria', 'croatia'],
  ['austria', 'czechia'],
  ['austria', 'germany'],
  ['austria', 'hungary'],
  ['austria', 'italy'],
  ['austria', 'poland'],
  ['austria', 'slovakia'],
  ['austria', 'slovenia'],
  ['austria', 'switzerland'],
  ['azerbaijan', 'georgia'],
  ['azerbaijan', 'iran'],
  ['azerbaijan', 'iraq'],
  ['azerbaijan', 'russia'],
  ['azerbaijan', 'turkey'],
  ['bangladesh', 'china'],
  ['bangladesh', 'india'],
  ['bangladesh', 'myanmar'],
  ['bangladesh', 'nepal'],
  ['belarus', 'estonia'],
  ['belarus', 'latvia'],
  ['belarus', 'lithuania'],
  ['belarus', 'poland'],
  ['belarus', 'russia'],
  ['belarus', 'ukraine'],
  ['belgium', 'france'],
  ['belgium', 'germany'],
  ['belgium', 'netherlands'],
  ['belgium', 'united_kingdom'],
  ['belize', 'el_salvador'],
  ['belize', 'guatemala'],
  ['belize', 'honduras'],
  ['belize', 'mexico'],
  ['benin', 'burkina_faso'],
  ['benin', 'ghana'],
  ['benin', 'niger'],
  ['benin', 'nigeria'],
  ['benin', 'togo'],
  ['bolivia', 'brazil'],
  ['bolivia', 'chile'],
  ['bolivia', 'paraguay'],
  ['bolivia', 'peru'],
  ['bosnia_and_herz', 'croatia'],
  ['bosnia_and_herz', 'hungary'],
  ['bosnia_and_herz', 'italy'],
  ['bosnia_and_herz', 'macedonia'],
  ['bosnia_and_herz', 'montenegro'],
  ['bosnia_and_herz', 'romania'],
  ['bosnia_and_herz', 'serbia'],
  ['bosnia_and_herz', 'slovenia'],
  ['botswana', 'mozambique'],
  ['botswana', 'namibia'],
  ['botswana', 'south_africa'],
  ['botswana', 'zambia'],
  ['botswana', 'zimbabwe'],
  ['brazil', 'colombia'],
  ['brazil', 'france'],
  ['brazil', 'guyana'],
  ['brazil', 'paraguay'],
  ['brazil', 'peru'],
  ['brazil', 'suriname'],
  ['brazil', 'uruguay'],
  ['brazil', 'venezuela'],
  ['bulgaria', 'greece'],
  ['bulgaria', 'macedonia'],
  ['bulgaria', 'moldova'],
  ['bulgaria', 'romania'],
  ['bulgaria', 'serbia'],
  ['bulgaria', 'turkey'],
  ['bulgaria', 'ukraine'],
  ['burkina_faso', 'cte_divoire'],
  ['burkina_faso', 'ghana'],
  ['burkina_faso', 'mali'],
  ['burkina_faso', 'niger'],
  ['burkina_faso', 'nigeria'],
  ['burkina_faso', 'togo'],
  ['burundi', 'dem_rep_congo'],
  ['burundi', 'rwanda'],
  ['burundi', 'tanzania'],
  ['burundi', 'uganda'],
  ['cambodia', 'laos'],
  ['cambodia', 'thailand'],
  ['cambodia', 'vietnam'],
  ['cameroon', 'central_african_rep'],
  ['cameroon', 'chad'],
  ['cameroon', 'congo'],
  ['cameroon', 'dem_rep_congo'],
  ['cameroon', 'eq_guinea'],
  ['cameroon', 'gabon'],
  ['cameroon', 'niger'],
  ['cameroon', 'nigeria'],
  ['canada', 'greenland'],
  ['canada', 'united_states_of_america'],
  ['central_african_rep', 'chad'],
  ['central_african_rep', 'congo'],
  ['central_african_rep', 'dem_rep_congo'],
  ['central_african_rep', 'gabon'],
  ['central_african_rep', 's_sudan'],
  ['central_african_rep', 'sudan'],
  ['chad', 'libya'],
  ['chad', 'niger'],
  ['chad', 'nigeria'],
  ['chad', 's_sudan'],
  ['chad', 'sudan'],
  ['chile', 'peru'],
  ['china', 'india'],
  ['china', 'kazakhstan'],
  ['china', 'kyrgyzstan'],
  ['china', 'laos'],
  ['china', 'mongolia'],
  ['china', 'myanmar'],
  ['china', 'nepal'],
  ['china', 'north_korea'],
  ['china', 'pakistan'],
  ['china', 'russia'],
  ['china', 'taiwan'],
  ['china', 'tajikistan'],
  ['china', 'thailand'],
  ['china', 'uzbekistan'],
  ['china', 'vietnam'],
  ['colombia', 'ecuador'],
  ['colombia', 'panama'],
  ['colombia', 'peru'],
  ['colombia', 'venezuela'],
  ['congo', 'dem_rep_congo'],
  ['congo', 'eq_guinea'],
  ['congo', 'gabon'],
  ['costa_rica', 'nicaragua'],
  ['costa_rica', 'panama'],
  ['croatia', 'hungary'],
  ['croatia', 'italy'],
  ['croatia', 'macedonia'],
  ['croatia', 'montenegro'],
  ['croatia', 'romania'],
  ['croatia', 'serbia'],
  ['croatia', 'slovakia'],
  ['croatia', 'slovenia'],
  ['cte_divoire', 'ghana'],
  ['cte_divoire', 'guinea'],
  ['cte_divoire', 'liberia'],
  ['cte_divoire', 'mali'],
  ['cte_divoire', 'sierra_leone'],
  ['cuba', 'mexico'],
  ['cuba', 'united_states_of_america'],
  ['czechia', 'germany'],
  ['czechia', 'hungary'],
  ['czechia', 'poland'],
  ['czechia', 'slovakia'],
  ['czechia', 'slovenia'],
  ['dem_rep_congo', 'gabon'],
  ['dem_rep_congo', 'malawi'],
  ['dem_rep_congo', 'mozambique'],
  ['dem_rep_congo', 'rwanda'],
  ['dem_rep_congo', 's_sudan'],
  ['dem_rep_congo', 'tanzania'],
  ['dem_rep_congo', 'uganda'],
  ['dem_rep_congo', 'zambia'],
  ['denmark', 'germany'],
  ['denmark', 'norway'],
  ['denmark', 'poland'],
  ['denmark', 'sweden'],
  ['ecuador', 'peru'],
  ['egypt', 'jordan'],
  ['egypt', 'libya'],
  ['egypt', 'saudi_arabia'],
  ['egypt', 'sudan'],
  ['egypt', 'syria'],
  ['el_salvador', 'guatemala'],
  ['el_salvador', 'honduras'],
  ['el_salvador', 'mexico'],
  ['el_salvador', 'nicaragua'],
  ['eq_guinea', 'gabon'],
  ['eritrea', 'ethiopia'],
  ['eritrea', 'sudan'],
  ['eritrea', 'yemen'],
  ['estonia', 'finland'],
  ['estonia', 'latvia'],
  ['estonia', 'lithuania'],
  ['estonia', 'russia'],
  ['ethiopia', 'kenya'],
  ['ethiopia', 's_sudan'],
  ['ethiopia', 'somalia'],
  ['ethiopia', 'sudan'],
  ['ethiopia', 'uganda'],
  ['ethiopia', 'yemen'],
  ['finland', 'norway'],
  ['finland', 'russia'],
  ['finland', 'sweden'],
  ['france', 'germany'],
  ['france', 'guyana'],
  ['france', 'italy'],
  ['france', 'netherlands'],
  ['france', 'spain'],
  ['france', 'suriname'],
  ['france', 'switzerland'],
  ['france', 'united_kingdom'],
  ['georgia', 'iran'],
  ['georgia', 'russia'],
  ['georgia', 'turkey'],
  ['germany', 'italy'],
  ['germany', 'netherlands'],
  ['germany', 'poland'],
  ['germany', 'slovenia'],
  ['germany', 'sweden'],
  ['germany', 'switzerland'],
  ['ghana', 'niger'],
  ['ghana', 'nigeria'],
  ['ghana', 'togo'],
  ['greece', 'italy'],
  ['greece', 'macedonia'],
  ['greece', 'montenegro'],
  ['greece', 'serbia'],
  ['greece', 'turkey'],
  ['guatemala', 'honduras'],
  ['guatemala', 'mexico'],
  ['guinea', 'liberia'],
  ['guinea', 'mali'],
  ['guinea', 'senegal'],
  ['guinea', 'sierra_leone'],
  ['guyana', 'suriname'],
  ['guyana', 'venezuela'],
  ['honduras', 'mexico'],
  ['honduras', 'nicaragua'],
  ['hungary', 'poland'],
  ['hungary', 'romania'],
  ['hungary', 'serbia'],
  ['hungary', 'slovakia'],
  ['hungary', 'slovenia'],
  ['hungary', 'ukraine'],
  ['iceland', 'united_kingdom'],
  ['india', 'myanmar'],
  ['india', 'nepal'],
  ['india', 'pakistan'],
  ['india', 'sri_lanka'],
  ['indonesia', 'malaysia'],
  ['indonesia', 'papua_new_guinea'],
  ['iran', 'iraq'],
  ['iran', 'oman'],
  ['iran', 'pakistan'],
  ['iran', 'russia'],
  ['iran', 'saudi_arabia'],
  ['iran', 'turkey'],
  ['iran', 'turkmenistan'],
  ['iran', 'united_arab_emirates'],
  ['iraq', 'jordan'],
  ['iraq', 'saudi_arabia'],
  ['iraq', 'syria'],
  ['iraq', 'turkey'],
  ['ireland', 'united_kingdom'],
  ['italy', 'macedonia'],
  ['italy', 'montenegro'],
  ['italy', 'slovenia'],
  ['italy', 'switzerland'],
  ['italy', 'tunisia'],
  ['japan', 'russia'],
  ['japan', 'south_korea'],
  ['jordan', 'saudi_arabia'],
  ['jordan', 'syria'],
  ['kazakhstan', 'kyrgyzstan'],
  ['kazakhstan', 'mongolia'],
  ['kazakhstan', 'russia'],
  ['kazakhstan', 'tajikistan'],
  ['kazakhstan', 'turkmenistan'],
  ['kazakhstan', 'uzbekistan'],
  ['kenya', 's_sudan'],
  ['kenya', 'somalia'],
  ['kenya', 'tanzania'],
  ['kenya', 'uganda'],
  ['kyrgyzstan', 'tajikistan'],
  ['kyrgyzstan', 'uzbekistan'],
  ['laos', 'myanmar'],
  ['laos', 'thailand'],
  ['laos', 'vietnam'],
  ['latvia', 'lithuania'],
  ['latvia', 'russia'],
  ['liberia', 'sierra_leone'],
  ['libya', 'niger'],
  ['libya', 'sudan'],
  ['libya', 'tunisia'],
  ['lithuania', 'poland'],
  ['lithuania', 'russia'],
  ['macedonia', 'montenegro'],
  ['macedonia', 'romania'],
  ['macedonia', 'serbia'],
  ['madagascar', 'mozambique'],
  ['malawi', 'mozambique'],
  ['malawi', 'tanzania'],
  ['malawi', 'zambia'],
  ['malawi', 'zimbabwe'],
  ['malaysia', 'philippines'],
  ['malaysia', 'thailand'],
  ['mali', 'mauritania'],
  ['mali', 'niger'],
  ['mali', 'senegal'],
  ['mauritania', 'morocco'],
  ['mauritania', 'senegal'],
  ['mauritania', 'w_sahara'],
  ['mexico', 'united_states_of_america'],
  ['moldova', 'romania'],
  ['moldova', 'ukraine'],
  ['mongolia', 'russia'],
  ['montenegro', 'serbia'],
  ['morocco', 'portugal'],
  ['morocco', 'spain'],
  ['morocco', 'w_sahara'],
  ['mozambique', 'south_africa'],
  ['mozambique', 'tanzania'],
  ['mozambique', 'zambia'],
  ['mozambique', 'zimbabwe'],
  ['myanmar', 'thailand'],
  ['myanmar', 'vietnam'],
  ['namibia', 'south_africa'],
  ['namibia', 'zambia'],
  ['namibia', 'zimbabwe'],
  ['netherlands', 'united_kingdom'],
  ['nicaragua', 'panama'],
  ['niger', 'nigeria'],
  ['niger', 'togo'],
  ['nigeria', 'togo'],
  ['north_korea', 'russia'],
  ['north_korea', 'south_korea'],
  ['norway', 'russia'],
  ['norway', 'sweden'],
  ['norway', 'united_kingdom'],
  ['oman', 'saudi_arabia'],
  ['oman', 'united_arab_emirates'],
  ['oman', 'yemen'],
  ['pakistan', 'tajikistan'],
  ['poland', 'romania'],
  ['poland', 'russia'],
  ['poland', 'slovakia'],
  ['poland', 'sweden'],
  ['poland', 'ukraine'],
  ['portugal', 'spain'],
  ['romania', 'serbia'],
  ['romania', 'slovakia'],
  ['romania', 'turkey'],
  ['romania', 'ukraine'],
  ['russia', 'turkey'],
  ['russia', 'ukraine'],
  ['russia', 'united_states_of_america'],
  ['rwanda', 'tanzania'],
  ['rwanda', 'uganda'],
  ['s_sudan', 'sudan'],
  ['s_sudan', 'uganda'],
  ['saudi_arabia', 'sudan'],
  ['saudi_arabia', 'syria'],
  ['saudi_arabia', 'united_arab_emirates'],
  ['saudi_arabia', 'yemen'],
  ['serbia', 'slovenia'],
  ['slovakia', 'slovenia'],
  ['slovakia', 'ukraine'],
  ['south_africa', 'zimbabwe'],
  ['syria', 'turkey'],
  ['tajikistan', 'turkmenistan'],
  ['tajikistan', 'uzbekistan'],
  ['tanzania', 'uganda'],
  ['tanzania', 'zambia'],
  ['thailand', 'vietnam'],
  ['turkmenistan', 'uzbekistan'],
  ['zambia', 'zimbabwe'],
];

// ── Map Construction ──

export function createDefaultMap(): GameMap {
  const territories = new Map<string, Territory>();
  const continents = new Map<string, Continent>();
  const adjacency = new Map<string, Set<string>>();

  // Build continents
  for (const def of CONTINENTS) {
    const territoryIds = TERRITORIES
      .filter((t) => t.continentId === def.id)
      .map((t) => t.id);
    continents.set(def.id, { ...def, territoryIds });
  }

  // Build territories (unowned, 0 troops)
  for (const def of TERRITORIES) {
    territories.set(def.id, {
      ...def,
      ownerId: null,
      troops: 0,
      fortLevel: 0,
      falloutTurns: 0,
    });
    adjacency.set(def.id, new Set());
  }

  // Build adjacency graph (bidirectional)
  for (const [a, b] of EDGES) {
    adjacency.get(a)!.add(b);
    adjacency.get(b)!.add(a);
  }

  return { territories, continents, adjacency };
}

// ── Adjacency Helpers ──

export function areAdjacent(map: GameMap, a: string, b: string): boolean {
  return map.adjacency.get(a)?.has(b) ?? false;
}

export function getNeighbors(map: GameMap, territoryId: string): string[] {
  return Array.from(map.adjacency.get(territoryId) ?? []);
}

export function getPlayerTerritories(map: GameMap, playerId: string): Territory[] {
  return Array.from(map.territories.values()).filter(
    (t) => t.ownerId === playerId
  );
}

export function playerOwnsContinent(map: GameMap, playerId: string, continentId: string): boolean {
  const continent = map.continents.get(continentId);
  if (!continent) return false;
  return continent.territoryIds.every(
    (tid) => map.territories.get(tid)?.ownerId === playerId
  );
}
